# Generated by Django 4.0.3 on 2022-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='description'),
        ),
    ]
