# Generated by Django 4.0.3 on 2022-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=150, null=True, verbose_name='description'),
        ),
    ]
