# Generated by Django 4.0.3 on 2022-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
