# Generated by Django 4.0.3 on 2022-03-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('descripion', models.TextField(max_length=255, verbose_name='descripion')),
                ('status', models.CharField(choices=[('D', 'done'), ('P', 'on progress'), ('S', 'sent')], default='S', max_length=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notes', to='team.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='task.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
