# Generated by Django 4.0.3 on 2022-03-18 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_descripion_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deadline'),
            preserve_default=False,
        ),
    ]
